"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
email = "pepijn.overbeeke@gmail.com"
name = "Pepijn Overbeeke"

[git]
push-new-bookmarks = true

[ui]
paginate = "never"
default-command = "log"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[[--scope]]
--when.commands = ["diff"]
ui.paginate = "auto"
