console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:blue'
    template = '<b>{{ .Path }}</b> '

    [blocks.segments.properties]
      style = 'letter'

  [[blocks.segments]]
    type = 'git'
    stype = 'plain'
    foreground = 'p:lavendar'
    background = 'transparent'
    template = '<b>{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}</b>{{ if .Detached }} detached{{ end }}{{ if .Merge }} merging{{ end }}{{ if .Rebase }} rebasing{{ end }}{{ if .CherryPick }} cherry-pick{{end}} '

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'

  [[blocks.segments]]
    type = "jujutsu"
    style = "plain"
    foreground = "#193549"
    background = "#ffeb3b"

    [blocks.segments.properties]
      ignore_working_copy = false

  [[blocks.segments]]
    type = 'nix-shell'
    stype = 'plain'
    foreground = 'p:red'
    background = 'transparent'
    template = '<b>{{ if hasSuffix "unknown" .Type }}{{else}}[󱄅] {{ .Type }}-shell {{end}}</b>'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'
    template = '{{ div .Ms 1000 }}'

    [blocks.segments.properties]
      threshold = 5000


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    foreground_templates = [
      "{{ if gt .Code 0 }}p:red{{ end }}",
      "{{ if eq .Code 0 }}p:sapphire{{ end }}",
    ]
    template = '<b>❯</b>'

[transient_prompt]
  foreground_templates = [
    "{{ if gt .Code 0 }}p:red{{ end }}",
    "{{ if eq .Code 0 }}p:sapphire{{ end }}",
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'p:sapphire'
  background = 'transparent'
  template = '❯❯ '

[palette]
rosewater = '#DC8A78'
flamingo = '#DD7878'
pink = '#EA76CB'
mauve = '#8839EF'
red = '#D20F39'
maroon = '#E64553'
peach = '#FE640B'
yellow = '#DF8E1D'
green = '#40A02B'
teal = '#179299'
sky = '#04A5E5'
sapphire = '#209FB5'
blue = '#1E66F5'
lavender = '#7287FD'
text = '#4C4F69'
subtext1 = '#5C5F77'
subtext0 = '#6C6F85'
overlay2 = '#7C7F93'
overlay1 = '#8C8FA1'
overlay0 = '#9CA0B0'
surface2 = '#ACB0BE'
surface1 = '#BCC0CC'
surface0 = '#CCD0DA'
base = '#EFF1F5'
mantle = '#E6E9EF'
crust = '#DCE0E8'
true = 'p:green'
false = 'p:red'
time = 'p:overlay1'
os-fg = 'p:base'
os-bg = 'p:overlay1'
root-fg = 'p:base'
root-bg = 'p:peach'
path = 'p:peach'
git = 'p:lavender'
docker = 'p:sky'
go = 'p:mauve'
haskell = 'p:mauve'
julia = 'p:mauve'
lua = 'p:mauve'
python = 'p:mauve'
rust = 'p:mauve'

