"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
email = "Pepijn.Overbeeke@triodos.com"
name = "Pepijn Overbeeke"

[ui]
paginate = "never"
default-command = "log"

[colors]
rest = "white"

[[--scope]]
--when.commands = ["diff"]
ui.paginate = "auto"
